stages:
  - build
  - test
  - deploy

variables:
  SPRING_PROFILES_ACTIVE: "dev"

before_script:
  - echo "SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE"

# Build stage
build_frontend:
  stage: build
  image: "node:20"
  before_script:
    - cd ./frontend/Re-Connect
    - npm install
  script:
    - npm run build

build_backend:
  stage: build
  image: maven:3.8.5-openjdk-17
  before_script:
    - cd ./backend
  script:
    - mvn clean package -DskipTests=true
  artifacts:
    paths:
      - target/*.jar

# Test stage
test:
  stage: test
  image: maven:3.8.5-openjdk-17
  before_script:
    - cd ./backend
  script:
    - mvn test
  only:
    - branches

# Deploy stage
deploy:
  stage: deploy
  image: eclipse-temurin:17-jre
  before_script:
    - cd ./backend
  script:
    - java -jar ./target/reconnect-0.0.1-SNAPSHOT.jar --spring.profiles.active=$SPRING_PROFILES_ACTIVE
  only:
    - dev
