stages:
  - build
  - test
  - deploy

variables:
  SPRING_PROFILES_ACTIVE: "dev"

before_script:
  - echo "SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE"

# Build stage
build_frontend:
  stage: build
  image: "node:10"
  working_dir: /frontend/Re-Connect
  before_script:
    - npm install
  script:
    - npm run build

build_backend:
  stage: build
  image: maven:3.8.5-openjdk-17
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

# Test stage
test:
  stage: test
  image: maven:3.8.5-openjdk-17
  script:
    - mvn test
  only:
    - branches

# Deploy stage
deploy:
  stage: deploy
  image: eclipse-temurin:17-jre
  script:
    - java -jar target/your-app-name.jar --spring.profiles.active=$SPRING_PROFILES_ACTIVE
  only:
    - master
